var NewProject = "var Midi = require('jsmidgen');\n"
+"var fs = require('fs');\n"
+"\n"
+"var file = new Midi.File();\n"
+"var track = new Midi.Track();\n"
+"file.addTrack(track);\n"
+"\n"
+"// add your notes here\n"
+"track.addNote(0, 'c4', 128);\n"
+"\n"
+"fs.writeFileSync('filename.mid', file.toBytes(), 'binary');\n";

var SimpleNotes = "var Midi = require('jsmidgen');\n"
+"var fs = require('fs');\n"
+"\n"
+"var file = new Midi.File();\n"
+"var track = new Midi.Track();\n"
+"file.addTrack(track);\n"
+"\n"
+"// add your notes here\n"
+"track.addNote(0, 'c4', 64);\n"
+"track.addNote(0, 'd4', 64);\n"
+"track.addNote(0, 'e4', 64);\n"
+"track.addNote(0, 'f4', 64);\n"
+"track.addNote(0, 'g4', 64);\n"
+"track.addNote(0, 'a4', 64);\n"
+"track.addNote(0, 'b4', 64);\n"
+"track.addNote(0, 'c5', 64);\n"
+"\n"
+"fs.writeFileSync('simple.mid', file.toBytes(), 'binary');\n";

var Loops = "var Midi = require('jsmidgen');\n"
+"var fs = require('fs');\n"
+"\n"
+"var file = new Midi.File();\n"
+"var track = new Midi.Track();\n"
+"file.addTrack(track);\n"
+"\n"
+"// add your notes here\n"
+"for (var i=0; i<3; i++) {\n"
+"\ttrack.addNote(0, 'c4', 32);\n"
+"\ttrack.addNote(0, 'd4', 64);\n"
+"\ttrack.addNote(0, 'e4', 96);\n"
+"\ttrack.addNote(0, '', 128); // leave note blank to rest\n"
+"}\n"
+"\n"
+"fs.writeFileSync('loop.mid', file.toBytes(), 'binary');\n";

var Functions = "var Midi = require('jsmidgen');\n"
+"var fs = require('fs');\n"
+"\n"
+"var file = new Midi.File();\n"
+"var track = new Midi.Track();\n"
+"file.addTrack(track);\n"
+"\n"
+"// add your notes here\n"
+"up();\n"
+"down();\n"
+"down();\n"
+"up();\n"
+"down();\n"
+"\n"
+"// here are the functions called above\n"
+"function up() {\n"
+"\ttrack.addNote(0, 'c4', 32);\n"
+"\ttrack.addNote(0, 'c4', 32);\n"
+"\ttrack.addNote(0, 'd4', 64);\n"
+"\ttrack.addNote(0, 'e4', 96);\n"
+"\ttrack.addNote(0, '', 128); // leave note blank to rest\n"
+"}\n"
+"\n"
+"function down() {\n"
+"\ttrack.addNote(0, 'e4', 64);\n"
+"\ttrack.addNote(0, 'd4', 64);\n"
+"\ttrack.addNote(0, 'c4', 96);\n"
+"\ttrack.addNote(0, '', 128); // leave note blank to rest\n"
+"}\n"
+"\n"
+"fs.writeFileSync('functions.mid', file.toBytes(), 'binary');\n";
